// Generated by: gen
// TypeWriter: slice
// Directive: +gen on String

package hugo

// StringSlice is a slice of type String. Use it where you would use []String.
type StringSlice []String

// SelectString projects a slice of string from StringSlice, typically called a map in other frameworks. See: http://clipperhouse.github.io/gen/#Select
func (rcv StringSlice) SelectString(fn func(String) string) (result []string) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}
