// Automatically generated by MockGen. DO NOT EDIT!
// Source: service/movabletype.go

package service

import (
	gomock "github.com/golang/mock/gomock"
)

// MockMovableType is a mock of MovableType interface
type MockMovableType struct {
	ctrl     *gomock.Controller
	recorder *MockMovableTypeMockRecorder
}

// MockMovableTypeMockRecorder is the mock recorder for MockMovableType
type MockMovableTypeMockRecorder struct {
	mock *MockMovableType
}

// NewMockMovableType creates a new mock instance
func NewMockMovableType(ctrl *gomock.Controller) *MockMovableType {
	mock := &MockMovableType{ctrl: ctrl}
	mock.recorder = &MockMovableTypeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockMovableType) EXPECT() *MockMovableTypeMockRecorder {
	return _m.recorder
}
